"""create shrimp catalog tables

Revision ID: 5479f052302a
Revises: 9e88ebf2685a
Create Date: 2026-08-08 12:40:20.787432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5479f052302a'
down_revision: Union[str, Sequence[str], None] = '9e88ebf2685a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shrimp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('species', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('grade', sa.String(length=64), nullable=True),
    sa.Column('rarity', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('catalog_status', sa.String(length=32), nullable=False),
    sa.Column('traits', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shrimp_catalog_status'), 'shrimp', ['catalog_status'], unique=False)
    op.create_index(op.f('ix_shrimp_name'), 'shrimp', ['name'], unique=False)
    op.create_table('care_parameters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shrimp_id', sa.UUID(), nullable=False),
    sa.Column('ph_min', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('ph_max', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('gh_min', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('gh_max', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('kh_min', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('kh_max', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('tds_min', sa.Integer(), nullable=True),
    sa.Column('tds_max', sa.Integer(), nullable=True),
    sa.Column('temperature_min', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('temperature_max', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.ForeignKeyConstraint(['shrimp_id'], ['shrimp.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shrimp_id')
    )
    op.create_table('shrimp_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shrimp_id', sa.UUID(), nullable=False),
    sa.Column('r2_key', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shrimp_id'], ['shrimp.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shrimp_images_shrimp_id'), 'shrimp_images', ['shrimp_id'], unique=False)
    op.create_table('shrimp_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shrimp_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sale_unit', sa.String(length=32), nullable=False),
    sa.Column('sale_quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_shrimp_variants_price_non_negative'),
    sa.CheckConstraint('sale_quantity IN (1, 5, 10)', name='ck_shrimp_variants_sale_quantity'),
    sa.CheckConstraint('stock_quantity >= 0', name='ck_shrimp_variants_stock_non_negative'),
    sa.ForeignKeyConstraint(['shrimp_id'], ['shrimp.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shrimp_variants_shrimp_id'), 'shrimp_variants', ['shrimp_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shrimp_variants_shrimp_id'), table_name='shrimp_variants')
    op.drop_table('shrimp_variants')
    op.drop_index(op.f('ix_shrimp_images_shrimp_id'), table_name='shrimp_images')
    op.drop_table('shrimp_images')
    op.drop_table('care_parameters')
    op.drop_index(op.f('ix_shrimp_name'), table_name='shrimp')
    op.drop_index(op.f('ix_shrimp_catalog_status'), table_name='shrimp')
    op.drop_table('shrimp')
    # ### end Alembic commands ###
