"""create user profiles and addresses

Revision ID: 6d8ef918ce6f
Revises: b6a1f3d82c44
Create Date: 2026-08-10 13:26:05.363457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d8ef918ce6f'
down_revision: Union[str, Sequence[str], None] = 'b6a1f3d82c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=False),
    sa.Column('recipient_phone_encrypted', sa.String(length=1024), nullable=False),
    sa.Column('address_line1_encrypted', sa.String(length=1024), nullable=False),
    sa.Column('address_line2_encrypted', sa.String(length=1024), nullable=True),
    sa.Column('suburb', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('postcode', sa.String(length=16), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_addresses_user_id'), 'user_addresses', ['user_id'], unique=False)
    op.create_index(
        'uq_user_addresses_one_default_per_user',
        'user_addresses',
        ['user_id'],
        unique=True,
        postgresql_where=sa.text('is_default = true'),
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone_encrypted', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column(
        'users',
        sa.Column(
            'status',
            sa.String(length=32),
            server_default='active',
            nullable=False,
        ),
    )
    op.alter_column('users', 'status', server_default=None)
    op.add_column('users', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deactivated_at')
    op.drop_column('users', 'status')
    op.drop_table('user_profiles')
    op.drop_index('uq_user_addresses_one_default_per_user', table_name='user_addresses')
    op.drop_index(op.f('ix_user_addresses_user_id'), table_name='user_addresses')
    op.drop_table('user_addresses')
    # ### end Alembic commands ###
