"""add refresh token lookup hash

Revision ID: 9e88ebf2685a
Revises: b19b4f08ca3e
Create Date: 2026-08-07 14:25:54.289583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e88ebf2685a'
down_revision: Union[str, Sequence[str], None] = 'b19b4f08ca3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('refresh_token_lookup_hash', sa.String(length=64), nullable=False))
    op.drop_index(op.f('ix_sessions_refresh_token_hash'), table_name='sessions')
    op.create_index(op.f('ix_sessions_refresh_token_lookup_hash'), 'sessions', ['refresh_token_lookup_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_refresh_token_lookup_hash'), table_name='sessions')
    op.create_index(op.f('ix_sessions_refresh_token_hash'), 'sessions', ['refresh_token_hash'], unique=False)
    op.drop_column('sessions', 'refresh_token_lookup_hash')
    # ### end Alembic commands ###
