"""add stripe payment fields

Revision ID: dfdf42b8c577
Revises: 3fe324011230
Create Date: 2026-08-12 18:44:36.949781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfdf42b8c577'
down_revision: Union[str, Sequence[str], None] = '3fe324011230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_event_id', name='uq_payment_events_provider_event_id')
    )
    op.create_index(op.f('ix_payment_events_event_type'), 'payment_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_payment_events_order_id'), 'payment_events', ['order_id'], unique=False)
    op.create_index(op.f('ix_payment_events_provider'), 'payment_events', ['provider'], unique=False)
    op.add_column('orders', sa.Column('payment_status', sa.String(length=32), server_default='pending', nullable=False))
    op.add_column('orders', sa.Column('payment_provider', sa.String(length=32), server_default='stripe', nullable=False))
    op.add_column('orders', sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('payment_failed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('cancelled_reason', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_orders_payment_provider'), 'orders', ['payment_provider'], unique=False)
    op.create_index(op.f('ix_orders_payment_status'), 'orders', ['payment_status'], unique=False)
    op.create_index(op.f('ix_orders_stripe_payment_intent_id'), 'orders', ['stripe_payment_intent_id'], unique=False)
    op.create_unique_constraint('uq_orders_stripe_checkout_session_id', 'orders', ['stripe_checkout_session_id'])
    op.alter_column('orders', 'payment_status', server_default=None)
    op.alter_column('orders', 'payment_provider', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_orders_stripe_checkout_session_id', 'orders', type_='unique')
    op.drop_index(op.f('ix_orders_stripe_payment_intent_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_provider'), table_name='orders')
    op.drop_column('orders', 'cancelled_reason')
    op.drop_column('orders', 'payment_failed_at')
    op.drop_column('orders', 'paid_at')
    op.drop_column('orders', 'stripe_payment_intent_id')
    op.drop_column('orders', 'stripe_checkout_session_id')
    op.drop_column('orders', 'payment_provider')
    op.drop_column('orders', 'payment_status')
    op.drop_index(op.f('ix_payment_events_provider'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_order_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_event_type'), table_name='payment_events')
    op.drop_table('payment_events')
    # ### end Alembic commands ###
